### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by dviljoen** [facebookincubator/memory-analyzer#16]
$ memory_analyzer run 7758 -e /usr/local/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/memory_analyzer", line 5, in <module>
    from memory_analyzer.memory_analyzer import cli
  File "/usr/local/lib/python3.8/site-packages/memory_analyzer/memory_analyzer.py", line 19, in <module>
    from . import analysis_utils
  File "/usr/local/lib/python3.8/site-packages/memory_analyzer/analysis_utils.py", line 23, in <module>
    from .frontend import frontend_utils
  File "/usr/local/lib/python3.8/site-packages/memory_analyzer/frontend/frontend_utils.py", line 7, in <module>
    import curses
  File "/usr/local/lib/python3.8/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by thatch** [comment]
Your python 3.8 install doesn't have a working "curses" library. Did you compile it yourself? You may have been missing a curses-devel type package.
