### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gdb': 'gdb'

### ISSUE THREAD

**Issue by hhimanshu** [facebookincubator/memory-analyzer#19]
Hello, When I run `memory_analyzer`, I get the following error

```
root@0d2c1ee9dd40:/app# memory_analyzer run 6
Analyzing pid 6
Setting up GDB for pid 6
Traceback (most recent call last):
  File "/usr/local/bin/memory_analyzer", line 8, in <module>
    sys.exit(cli())
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/memory_analyzer/memory_analyzer.py", line 211, in run
    for result in worker_pool.imap_unordered(target, pids):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/site-packages/memory_analyzer/memory_analyzer.py", line 40, in analyze_memory_launcher
    return gdb_obj.run_analysis(debug)
  File "/usr/local/lib/python3.6/site-packages/memory_analyzer/analysis_utils.py", line 78, in run_analysis
    command, stderr=sys.stderr if debug else subprocess.DEVNULL
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gdb': 'gdb'
```

I am using Python 3.6 version
```
root@0d2c1ee9dd40:/app# python --version
Python 3.6.10
```
I am running this inside Docker, and see the following message where all necessary dependencies are added
```
Installing collected packages: prettytable, pympler, graphviz, objgraph, memory-analyzer
Successfully installed graphviz-0.15 memory-analyzer-0.1.2 objgraph-3.5.0 prettytable-2.0.0 pympler-0.9
```

Please let me know what I am missing. Thank you

**Comment by thatch** [comment]
Can you try running `gdb` yourself?  I suspect it's not installed.

**Comment by hhimanshu** [comment]
Yes, that was the issue. Thanks, now I am getting another error, but working to see if I can fix that! Thanks for the response
